[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#294190'

[colors.cursor]
text = '#131313'
cursor = '#b7c4ff'

[colors.normal]
black   = '#131313'
red     = '#ff7297'
green   = '#7fff94'
yellow  = '#fff972'
blue    = '#a0aef2'
magenta = '#384376'
cyan    = '#b7c4ff'
white   = '#eff2ff'

[colors.bright]
black   = '#999ba5'
red     = '#ff9fb8'
green   = '#a5ffb4'
yellow  = '#fffba5'
blue    = '#c1ccff'
magenta = '#ccd5ff'
cyan    = '#dee4ff'
white   = '#f8f9ff'
