##### PREFIX KEY #####
# Use Shift+Enter as prefix
# unbind C-b
# set -g prefix S-Enter
# bind S-Enter send-prefix

# Use Shift+Enter as prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

##### GENERAL SETTINGS #####
set -g mouse on
set -g history-limit 10000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 0
set -g focus-events on

##### TRUE COLOR SUPPORT #####
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -as terminal-overrides ",*:Tc"

##### SPLITS (vim style) #####
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

##### PANE NAVIGATION (vim keys) #####
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

##### RESIZE PANES #####
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind-key S-Enter set-option -g status

##### COPY MODE (vim style) #####
setw -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

##### SCROLL WITH MOUSE & COPY #####
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel

##### RELOAD CONFIG #####
bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

##### STATUS BAR #####
set -g status-position bottom
set -g status-interval 5

set -g status-left "#[bold]#S "
set -g status-right "%Y-%m-%d %H:%M "

##### WINDOW NAVIGATION #####
bind-key n next-window
bind-key p previous-window

##### START WINDOWS AND PANES AT 1 #####
set -g base-index 1
setw -g pane-base-index 1

##### BETTER NEW WINDOW #####
bind c new-window -c "#{pane_current_path}"

##### BETTER SPLIT PATH #####
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


##### shortcut for changing terminals #######
bind -n M-e select-window -t 1
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-9 select-window -t 9
bind -n M-8 select-window -t 8
