#!/bin/bash

TIME=$(date '+%H:%M')
DAY=$(date '+%a')

RAM=$(free -h | awk '/Mem:/ {print $3}')

# BAT_PATH="/sys/class/power_supply/BAT0"
BAT_PATH=$(ls -d /sys/class/power_supply/BAT* 2>/dev/null | head -n 1)
if [ -d "$BAT_PATH" ]; then
    BAT=$(cat "$BAT_PATH/capacity" 2>/dev/null)
    STATUS=$(cat "$BAT_PATH/status" 2>/dev/null)

    if [ -n "$BAT" ]; then
        if [ "$BAT" -ge 80 ]; then BASE=""
        elif [ "$BAT" -ge 60 ]; then BASE=""
        elif [ "$BAT" -ge 40 ]; then BASE=""
        elif [ "$BAT" -ge 20 ]; then BASE=""
        else BASE=""
        fi

        if [ "$STATUS" = "Charging" ]; then
            ICON=" $BASE"
        elif [ "$STATUS" = "Full" ]; then
            ICON=" $BASE"
        else
            ICON="$BASE"
        fi

        BAT_TEXT="$ICON ${BAT}%"
    fi
fi

TEXT="  $RAM  •  󰥔 $DAY $TIME"
[ -n "$BAT_TEXT" ] && TEXT="$TEXT  •  $BAT_TEXT"

notify-send -a statusbar -r 999 \
    -h string:x-canonical-private-synchronous:statusbar "$TEXT"
