#!/bin/bash

PIDFILE="/tmp/statusbar.pid"

if [ -f "$PIDFILE" ]; then
    kill "$(cat "$PIDFILE")" 2>/dev/null
    rm "$PIDFILE"
    makoctl dismiss -a statusbar
else
    statusbar &
    echo $! > "$PIDFILE"
fi
